import mongoose from 'mongoose';

const vehicleSchema = new mongoose.Schema({
    owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    listingIntent: { type: String, required: true },
    category: String,
    subcategory: String,
    vehicleCompany: String,
    vehicleName: String,
    modelYear: String,
    vehicleNumber: { type: String, required: true },
    mileage: String,
    fuelAverage: String,
    engineSize: String,
    horsepower: String,
    registrationCity: String,
    color: String,
    seats: String,
    doors: String,
    fuelType: String,
    condition: String,
    transmission: String,
    driveType: String,
    assembly: String,
    features: {
        airConditioner: Boolean,
        leatherSeats: Boolean,
        powerWindows: Boolean,
        pushStart: Boolean,
        digitalOdometer: Boolean,
        steeringAdjustment: Boolean,
        ambientLighting: Boolean,
        airbags: Boolean,
        antiLockBraking: Boolean,
        immobilizer: Boolean,
        parkingSensors: Boolean,
        stabilityControl: Boolean,
        tractionControl: Boolean,
        centralLocking: Boolean,
        androidAuto: Boolean,
        appleCarPlay: Boolean,
        bluetooth: Boolean,
        climateControl: Boolean,
        cruiseControl: Boolean,
        keylessEntry: Boolean,
        powerSteering: Boolean,
    },
    sellingPrice: String,
    isPriceNegotiable: Boolean,
    vehicleDescription: String,
    media: {
        frontView: String,
        backView: String,
        leftSide: String,
        rightSide: String,
        interior: String,
        dashboard: String,
        engineBay: String,
        exteriorDetail: String,
    },
    legal: {
        cnicFront: String,
        cnicBack: String,
        registrationBook: String,
        verificationCertificate: String,
        transferDeed: String,
        insurancePapers: String,
    },
    sellerName: String,
    sellerPhone: String,
    sellerEmail: String,
    sellerLoc: String,
    socialHandle: String,
    availability: String,
    preferredContact: String,
    status: { type: String, default: "pending", enum: ["approved", "pending", "rejected"] },
    isActive: { type: Boolean, default: false }
}, { timestamps: true });

const Vehicle = mongoose.models.Vehicle || mongoose.model("Vehicle", vehicleSchema);
export default Vehicle;